[package]
name = "wirc_server"
version = "0.1.0"
authors = ["willemml"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
warp = "0.2.5"
reqwest = { version = "0.10", features = ["json", "blocking"] }
uuid = { version = "0.8", features = ["serde", "v4"]}
rand = "0.7.3"
oauth2 = "3.0.0"
serde_json = "1.0.59"
serde = "1.0.117"
serde_bytes = "0.11"
futures = "0.3"
sha2 = "0.9.2"
