[package]
name = "wirc_server"
version = "0.1.0"
authors = ["willemml"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
warp = "0.2.5"
reqwest = { version = "0.10", features = ["json"] }
uuid = { version = "0.8", features = ["serde", "v4"]}
rand = "0.7.3"
oauth2 = "3.0.0"
rusqlite = { version = "0.23.1", features = ["bundled", "uuid"] }
